import type { Company, Category, NewsItem } from "./types/company";

export const categories: Category[] = [
  { label: "All",                    slug: "all" },
  { label: "Technology",             slug: "technology" },
  { label: "Business & Manpower",    slug: "business-services" },
  { label: "Marketing & Trading",    slug: "marketing" },
  { label: "Construction",           slug: "construction" },
  { label: "Professional Services",  slug: "professional" },
  { label: "Other Services",         slug: "other" },
  { label: "Foundation",             slug: "foundation" },
];

export const companies: Company[] = [
  {
    id: "brains-infinite",
    name: "Brains Infinite Innovations",
    category: "Technology & Innovation",
    categorySlug: "technology",
    tagline: "Reliable solutions for you, your company, and the nation",
    description:
      "Brains Infinite Innovations Inc. is a group of competent professionals who are dedicated in creating reliable solutions to assist you, your company, and the whole of the nation's economy.",
    services: ["Software Development", "IT Consulting", "Digital Solutions", "Systems Integration"],
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop&auto=format",
    website: "https://www.brains.asia/",
    facebook: "https://www.facebook.com/brains.asia",
    instagram: "https://www.instagram.com/brainstech.ph/",
    youtube: "https://www.youtube.com/watch?v=Ukgl6BNDJMM",
  },
  {
    id: "klassic-solutions",
    name: "Klassic Solutions Inc.",
    category: "Business & Manpower Services",
    categorySlug: "business-services",
    tagline: "Creative manpower solutions for Philippine business",
    description:
      "Klassic Solutions Inc. is a manpower services organization dedicated in providing creative solutions to companies across a wide spectrum of Philippine business according to their specific needs and requirements.",
    services: ["Manpower Outsourcing", "Recruitment", "Workforce Deployment", "HR Consulting"],
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop&auto=format",
    website: "https://connectorcore.com/Klassic-Solutions-PH-master/",
    facebook: "https://www.facebook.com/klassiclink",
    instagram: "https://www.instagram.com/klassicsolutions.ph/",
    youtube: "https://www.youtube.com/watch?v=2DDfh9bgNiA",
  },
  {
    id: "klassic-marketing",
    name: "Klassic Marketing Inc.",
    category: "Marketing & Trading",
    categorySlug: "marketing",
    tagline: "Your gateway to global market access",
    description:
      "Klassic Marketing Inc. is formed to serve as an avenue for enterprises having global market access in importation and trading while processing transactions through Portress.",
    services: ["Importation", "Trading", "Global Market Access", "Transaction Processing"],
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=400&fit=crop&auto=format",
    website: "https://connectorcore.com/Klassic-Marketing-Inc-Website-master",
    facebook: "https://www.facebook.com/klassicmarketingincv",
    instagram: "https://www.instagram.com/klassicmarketing.ph/",
    youtube: "#",
  },
  {
    id: "westwood-development",
    name: "Westwood Development Corp.",
    category: "Construction & Development",
    categorySlug: "construction",
    tagline: "Changing traditional methodologies in construction",
    description:
      "Westwood Development Corp. is driven by a group of individuals who are passionate about changing traditional methodologies in the construction and development industry.",
    services: ["Real Estate Development", "General Construction", "Project Management", "Property Development"],
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&h=400&fit=crop&auto=format",
    website: "https://connectorcore.com/Westwood-Development-Corp-Website-master/",
    facebook: "https://www.facebook.com/Westwooddevcorp",
    instagram: "https://www.instagram.com/westwood.dev/",
    youtube: "#",
  },
  {
    id: "westwood-law",
    name: "Westwood Law Firm",
    category: "Professional Services",
    categorySlug: "professional",
    tagline: "Expert legal counsel for every case",
    description:
      "Westwood Law Firm is a law firm that deals with the specialized practice of law to ensure that all cases are handled by the experts in the field of law where the case falls under.",
    services: ["Corporate Law", "Litigation", "Legal Advisory", "Case Management"],
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&h=400&fit=crop&auto=format",
    website: "https://connectorcore.com/Westwood-Law-Firm-Website-master/",
    facebook: "https://www.facebook.com/westwoodlawph",
    instagram: "https://www.instagram.com/westwood.law/",
    youtube: "#",
  },
  {
    id: "connector",
    name: "Connector",
    category: "Technology & Innovation",
    categorySlug: "technology",
    tagline: "Connecting systems, bringing people together",
    description:
      "Connector is a system designed as a modular software system that aims to integrate the main functional areas of an organization's business processes into a unified system.",
    services: ["ERP Integration", "Business Process Automation", "Modular Software", "Systems Connectivity"],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop&auto=format",
    website: "https://connectorcore.com/Connector-Website-master/",
    facebook: "https://www.facebook.com/connectormode",
    instagram: "https://www.instagram.com/connector.mode/",
    youtube: "#",
  },
  {
    id: "green-oasis",
    name: "The Green Oasis",
    category: "Other Services",
    categorySlug: "other",
    tagline: "Landscape and design specialists",
    description:
      "The Green Oasis is a professional landscape and design specialists dedicated to providing landscape quality services; designing attractive spaces and maintaining their functionality and beauty for homeowners.",
    services: ["Landscape Design", "Garden Maintenance", "Space Design", "Outdoor Beautification"],
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop&auto=format",
    website: "https://connectorcore.com/The-Green-Oasis-Website-master",
    facebook: "https://www.facebook.com/thregreenoasisph",
    instagram: "https://www.instagram.com/thegreenoasisph/",
    youtube: "#",
  },
  {
    id: "luxurious-cleaning",
    name: "Luxurious Cleaning Co.",
    category: "Other Services",
    categorySlug: "other",
    tagline: "Trust and excellence in every clean",
    description:
      "Luxurious Cleaning Co. introduced itself in the cleaning industry in September 2019. Although new in the game, it gained TRUST and a STRONG POOL OF CLIENTS through consistent quality service.",
    services: ["Residential Cleaning", "Commercial Cleaning", "Deep Cleaning", "Janitorial Services"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&h=400&fit=crop&auto=format",
    website: "https://connectorcore.com/Luxurious-Cleaning-Website-master",
    facebook: "https://www.facebook.com/luxuriouscleaningph",
    instagram: "https://www.instagram.com/luxuriouscleaningco/",
    youtube: "#",
  },
  {
    id: "hyt-foundation",
    name: "HYT Foundation Inc.",
    category: "Foundation",
    categorySlug: "foundation",
    tagline: "Empowering the next generation of leaders",
    description:
      "HYT Foundation Inc. is a foundation for future generation leaders in which we support to enlighten and hone the youth in acquiring an adept set of business skills to prepare them for their future.",
    services: ["Youth Development", "Business Skills Training", "Leadership Programs", "Community Outreach"],
    image: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=600&h=400&fit=crop&auto=format",
    website: "https://connectorcore.com/HYT-Foundation-Inc-Website-master/",
    facebook: "https://www.facebook.com/profile.php?id=100085879536889",
    instagram: "https://www.instagram.com/connector.mode/",
    youtube: "#",
  },
  {
    id: "finest-fit",
    name: "The Finest Fit",
    category: "Other Services",
    categorySlug: "other",
    tagline: "High-quality uniforms that leave a great impression",
    description:
      "The Finest Fit strives to deliver high-quality uniforms that leave a great impression on our customers and establish ourselves as the best uniform company in the Philippines.",
    services: ["Uniform Manufacturing", "Custom Design", "Corporate Uniforms", "School Uniforms"],
    image: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&h=400&fit=crop&auto=format",
    website: "https://connectorcore.com/The-Finest-Fit-Website-master/",
    facebook: "https://www.facebook.com/thefinestfit",
    instagram: "https://www.instagram.com/connector.mode/",
    youtube: "#",
  },
];

export const newsItems = [
  {
    id: 1,
    category: "Company News",
    date: "September 5, 2026",
    title: "Klassic Group Expands Technology Division with New Innovation Hub",
    excerpt:
      "Klassic Group of Companies announces the launch of a new innovation center, accelerating digital transformation across its portfolio of companies.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: 2,
    category: "Community",
    date: "August 20, 2026",
    title: "HYT Foundation Awards Scholarships to Deserving Students",
    excerpt:
      "The HYT Foundation, in partnership with local universities, has awarded scholarships to outstanding students across Luzon, Visayas, and Mindanao.",
    image: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: 3,
    category: "Career Opportunities",
    date: "August 10, 2026",
    title: "Klassic Group Now Hiring Across Multiple Disciplines",
    excerpt:
      "Join a growing organization with career openings in technology, marketing, legal, and operations. Klassic Group of Companies is actively recruiting top talent.",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=400&fit=crop&auto=format",
  },
];
